### ISSUE TITLE
uninitialized memory usage in test_devicelist_create when running test_libomemo

### ISSUE THREAD

**Issue by hades** [gkdr/libomemo#53]
```
Uninitialized bytes in __interceptor_strcmp at offset 5 inside [0x701000000000, 6)
==16609==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f5f0a5362ce in string_equal_display_error obj-x86_64-linux-gnu/src/./src/cmocka.c:1296:9
    #1 0x7f5f0a5362ce in _assert_string_equal obj-x86_64-linux-gnu/src/./src/cmocka.c:1816:10
    #2 0x5628234dff5d in test_devicelist_create /home/hades/dev/libomemo/test/test_libomemo.c:61:3
    #3 0x7f5f0a536aab in cmocka_run_one_test_or_fixture obj-x86_64-linux-gnu/src/./src/cmocka.c:2801:13
    #4 0x7f5f0a537192 in cmocka_run_one_tests obj-x86_64-linux-gnu/src/./src/cmocka.c:2909:14
    #5 0x7f5f0a537192 in _cmocka_run_group_tests obj-x86_64-linux-gnu/src/./src/cmocka.c:3040:18
    #6 0x5628234f1d57 in main /home/hades/dev/libomemo/test/test_libomemo.c:1452:10
    #7 0x7f5f09e23a8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #8 0x7f5f09e23b48 in __libc_start_main csu/../csu/libc-start.c:360:3
    #9 0x56282343f5b4 in _start (/home/hades/dev/libomemo/build/test_libomemo+0x265b4) (BuildId: f0f27f1571dfa7d462937446f58512578187038c)
```

**Comment by Neustradamus** [comment]
@hades: Have you progressed on it?

**Comment by hades** [comment]
I think this was also an instrumentation error, I'll close it.
