### ISSUE TITLE
uninitialized memory usage in db_conn_open_and_prepare when running test_storage

### ISSUE THREAD

**Issue by hades** [gkdr/libomemo#54]
```
Uninitialized bytes in __interceptor_strlen at offset 0 inside [0x719000000008, 43)
==16613==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fe266ac7df1 in sqlite3Strlen30 /build/sqlite3-tqfYqM/sqlite3-3.40.1/./src/util.c:81:28
    #1 0x7fe266a92c75 in sqlite3PagerOpen /build/sqlite3-tqfYqM/sqlite3-3.40.1/./src/pager.c:4739:17
    #2 0x7fe266a17204 in sqlite3BtreeOpen /build/sqlite3-tqfYqM/sqlite3-3.40.1/./src/btree.c:2577:10
    #3 0x7fe266a8e172 in openDatabase /build/sqlite3-tqfYqM/sqlite3-3.40.1/./src/main.c:3406:8
    #4 0x5622240c49f7 in db_conn_open_and_prepare /home/hades/dev/libomemo/test/../src/libomemo_storage.c:46:13
    #5 0x5622240c4396 in omemo_storage_user_device_id_save /home/hades/dev/libomemo/test/../src/libomemo_storage.c:106:13
    #6 0x5622240c7651 in test_devicelist_save_id /home/hades/dev/libomemo/test/test_storage.c:34:17
    #7 0x7fe266de7aab in cmocka_run_one_test_or_fixture obj-x86_64-linux-gnu/src/./src/cmocka.c:2801:13
    #8 0x7fe266de8192 in cmocka_run_one_tests obj-x86_64-linux-gnu/src/./src/cmocka.c:2909:14
    #9 0x7fe266de8192 in _cmocka_run_group_tests obj-x86_64-linux-gnu/src/./src/cmocka.c:3040:18
    #10 0x5622240c9387 in main /home/hades/dev/libomemo/test/test_storage.c:156:10
    #11 0x7fe266623a8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #12 0x7fe266623b48 in __libc_start_main csu/../csu/libc-start.c:360:3
    #13 0x562224026584 in _start (/home/hades/dev/libomemo/build/test_storage+0x25584) (BuildId: 4d90a763c74f8bf950fe633297af2d17a6b0b303)
```

**Comment by hades** [comment]
This (and #53) could just be instrumentation errors, since my sqlite is not built with MSAN. I'll investigate and report back.

**Comment by Neustradamus** [comment]
@hades: Have you progressed on it?

**Comment by Neustradamus** [comment]
@hades: Why have you closed it? :/

**Comment by hades** [comment]
As I mentioned, this was an instrumentation error, I just forgot to update the issue. Thanks for checking!

**Comment by gkdr** [comment]
Thanks for taking a look in any case! Feel free to report anything else you might find.
